### PR TITLE
Upgrade to lts-19.18.

### PR DESCRIPTION
**Pull request by rickowens**

### CODE REVIEW

**Review by ollef — APPROVED** [review]

**Comment by joshburgess** [comment]
Can we merge this?

**Comment by ollef** [comment]
I no longer have commit access since I no longer work at Folq. @folq?

**Comment by joshburgess** [comment]
Okay. Yeah, it would be good to update this if we can. Right now, users of the library cannot update their projects to GHC 9 & above.

**Comment by rickowens** [comment]
I am willing to help maintain this project, if that would be helpful.

**Comment by vladimirlogachev** [comment]
Is this PR going to be merged any time soon?

**Comment by VKFisher** [comment]
This PR has been open for a while. Any chance this could be merged soon? This is blocking an lts bump in one of our projects. Happy to help if there's anything holding it up.

**Comment by ollef** [comment]
If you'd like to update this on Hackage, I've invited you as a maintainer on Hackage @rickowens. If anyone else wants access to make an update, let me know.

**Comment by rickowens** [comment]
> If you'd like to update this on Hackage, I've invited you as a maintainer on Hackage @rickowens. If anyone else wants access to make an update, let me know.

Thank you! I'll likely be able to do this in the next week, but probably not within the next day or two.

**Pull request merged**
