### PR TITLE
Support generics-sop 0.4.0 and 0.5.0

### PR DESCRIPTION
**Pull request by pjones**
Thanks for this very useful package!

### CODE REVIEW

**Review by ollef — CHANGES_REQUESTED** [review]
Hey thanks!

I don't think the generics-sop bounds are correct as they are now, because the code will no longer compile with the old version now that we've added another constructor field. To solve this in a way that's backward compatible I think we'll have to use some CPP.

It's currently a requirement from Folq's side to be backward compatible, as we haven't upgraded to LTS 15 yet.

**Comment by pjones** [comment]
Yep, I completely missed the lower bounds problem.

Using CPP sounds terrible.  Would it be possible to merge this into a different branch such as `next` or `develop`?  Does Folq directly use the master branch?  What about pinning to a tagged commit?

**Comment by ollef** [comment]
Actually, maybe we could try using [this function](https://hackage.haskell.org/package/generics-sop-0.5.0.0/docs/Generics-SOP.html#v:constructorInfo) instead of pattern matching to maintain compatibility while avoiding CPP?

I'd prefer keeping the latest version compatible with LTS 14, at least for some time, so we can continue using it.

**Comment by ollef** [comment]
Super, thanks! Nice that it reduces some duplication as well.

**Pull request merged**
